name: auto reply after pr is merged

on:
  pull_request:
    types: [closed]
    #branches: [main]

jobs:
  action:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: prs-reply
        uses: ./.github/actions/pr-reply
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}